# -*- coding: utf-8 -*-
"""impacto dos juros

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIrRPN17V8QSvQ8o05A3ZD7PY2M4L7cD
"""

PV = 750000
n = 420
taxa_juros_10 = 10 / 100 / 12
taxa_juros_115 = 11.5 / 100 / 12

def calcular_parcela(PV, i, n):
    PMT = PV * i / (1 - (1 + i) ** -n)
    return PMT

parcela_10 = calcular_parcela(PV, taxa_juros_10, n)
parcela_115 = calcular_parcela(PV, taxa_juros_115, n)

total_pago_10 = parcela_10 * n
total_pago_115 = parcela_115 * n

parcela_10, total_pago_10, parcela_115, total_pago_115